
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-11-19T18:01:35.733+01:00
 * Generated source version: 3.4.1
 *
 */

@javax.jws.WebService(
                      serviceName = "Service",
                      portName = "BasicHttpBinding_IService",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/c:/test/UgyfelhivoService_v1_Proxy_Service_WSDL.wsdl",
                      endpointInterface = "org.tempuri.IService")

public class BasicHttpBinding_IServiceImpl implements IService {

    private static final Logger LOG = Logger.getLogger(BasicHttpBinding_IServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.IService#getBranchStates(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.GetBranchStates parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.GetBranchStatesResponse parameters1)*
     */
    public void getBranchStates(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, GetBranchStates parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<GetBranchStatesResponse> parameters1) {
        LOG.info("Executing operation getBranchStates");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.GetBranchStatesResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#revokeBookingTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.RevokeBookingTicket parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.RevokeBookingTicketResponse parameters1)*
     */
    public void revokeBookingTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, RevokeBookingTicket parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<RevokeBookingTicketResponse> parameters1) {
        LOG.info("Executing operation revokeBookingTicket");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.RevokeBookingTicketResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#getActiveTickets(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.GetActiveTickets parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.GetActiveTicketsResponse parameters1)*
     */
    public void getActiveTickets(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, GetActiveTickets parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<GetActiveTicketsResponse> parameters1) {
        LOG.info("Executing operation getActiveTickets");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.GetActiveTicketsResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#getBranches(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.GetBranches parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.GetBranchesResponse parameters1)*
     */
    public void getBranches(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, GetBranches parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<GetBranchesResponse> parameters1) {
        LOG.info("Executing operation getBranches");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.GetBranchesResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#getFreeTimes(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.GetFreeTimes parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.GetFreeTimesResponse parameters1)*
     */
    public void getFreeTimes(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, GetFreeTimes parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<GetFreeTimesResponse> parameters1) {
        LOG.info("Executing operation getFreeTimes");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.GetFreeTimesResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#addBookingTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.AddBookingTicket parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.AddBookingTicketResponse parameters1)*
     */
    public void addBookingTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, AddBookingTicket parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<AddBookingTicketResponse> parameters1) {
        LOG.info("Executing operation addBookingTicket");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.AddBookingTicketResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#addTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.AddTicket parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.AddTicketResponse parameters1)*
     */
    public void addTicket(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, AddTicket parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<AddTicketResponse> parameters1) {
        LOG.info("Executing operation addTicket");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.AddTicketResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IService#getLanguages(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, org.tempuri.GetLanguages parameters, hu.posta.xmlns.common.ResponseHeaderType responsecommonheader, org.tempuri.GetLanguagesResponse parameters1)*
     */
    public void getLanguages(hu.posta.xmlns.common.RequestHeaderType requestcommonheader, GetLanguages parameters, javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader, javax.xml.ws.Holder<GetLanguagesResponse> parameters1) {
        LOG.info("Executing operation getLanguages");
        System.out.println(requestcommonheader);
        System.out.println(parameters);
        try {
            hu.posta.xmlns.common.ResponseHeaderType responsecommonheaderValue = null;
            responsecommonheader.value = responsecommonheaderValue;
            org.tempuri.GetLanguagesResponse parameters1Value = null;
            parameters1.value = parameters1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
