
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-11-19T18:01:35.869+01:00
 * Generated source version: 3.4.1
 *
 */

public class IService_BasicHttpBindingIService_Server{

    protected IService_BasicHttpBindingIService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BasicHttpBinding_IServiceImpl();
        String address = "http://localhost:8731/PostaInterfaceService/";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new IService_BasicHttpBindingIService_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
