package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-11-19T18:01:35.853+01:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.aquis_qcontrol_servermodules.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.aquis_qcontrol_servermodules_postainterface.ObjectFactory.class, hu.posta.xmlns.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IService {

    @WebMethod(operationName = "GetBranchStates", action = "http://tempuri.org/IService/GetBranchStates")
    @Action(input = "http://tempuri.org/IService/GetBranchStates", output = "http://tempuri.org/IService/GetBranchStatesResponse")
    public void getBranchStates(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "GetBranchStates", targetNamespace = "http://tempuri.org/")
        GetBranchStates parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "GetBranchStatesResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<GetBranchStatesResponse> parameters1
    );

    @WebMethod(operationName = "RevokeBookingTicket", action = "http://tempuri.org/IService/RevokeBookingTicket")
    @Action(input = "http://tempuri.org/IService/RevokeBookingTicket", output = "http://tempuri.org/IService/RevokeBookingTicketResponse")
    public void revokeBookingTicket(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "RevokeBookingTicket", targetNamespace = "http://tempuri.org/")
        RevokeBookingTicket parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "RevokeBookingTicketResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<RevokeBookingTicketResponse> parameters1
    );

    @WebMethod(operationName = "GetActiveTickets", action = "http://tempuri.org/IService/GetActiveTickets")
    @Action(input = "http://tempuri.org/IService/GetActiveTickets", output = "http://tempuri.org/IService/GetActiveTicketsResponse")
    public void getActiveTickets(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "GetActiveTickets", targetNamespace = "http://tempuri.org/")
        GetActiveTickets parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "GetActiveTicketsResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<GetActiveTicketsResponse> parameters1
    );

    @WebMethod(operationName = "GetBranches", action = "http://tempuri.org/IService/GetBranches")
    @Action(input = "http://tempuri.org/IService/GetBranches", output = "http://tempuri.org/IService/GetBranchesResponse")
    public void getBranches(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "GetBranches", targetNamespace = "http://tempuri.org/")
        GetBranches parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "GetBranchesResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<GetBranchesResponse> parameters1
    );

    @WebMethod(operationName = "GetFreeTimes", action = "http://tempuri.org/IService/GetFreeTimes")
    @Action(input = "http://tempuri.org/IService/GetFreeTimes", output = "http://tempuri.org/IService/GetFreeTimesResponse")
    public void getFreeTimes(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "GetFreeTimes", targetNamespace = "http://tempuri.org/")
        GetFreeTimes parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "GetFreeTimesResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<GetFreeTimesResponse> parameters1
    );

    @WebMethod(operationName = "AddBookingTicket", action = "http://tempuri.org/IService/AddBookingTicket")
    @Action(input = "http://tempuri.org/IService/AddBookingTicket", output = "http://tempuri.org/IService/AddBookingTicketResponse")
    public void addBookingTicket(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "AddBookingTicket", targetNamespace = "http://tempuri.org/")
        AddBookingTicket parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "AddBookingTicketResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<AddBookingTicketResponse> parameters1
    );

    @WebMethod(operationName = "AddTicket", action = "http://tempuri.org/IService/AddTicket")
    @Action(input = "http://tempuri.org/IService/AddTicket", output = "http://tempuri.org/IService/AddTicketResponse")
    public void addTicket(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "AddTicket", targetNamespace = "http://tempuri.org/")
        AddTicket parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "AddTicketResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<AddTicketResponse> parameters1
    );

    @WebMethod(operationName = "GetLanguages", action = "http://tempuri.org/IService/GetLanguages")
    @Action(input = "http://tempuri.org/IService/GetLanguages", output = "http://tempuri.org/IService/GetLanguagesResponse")
    public void getLanguages(

        @WebParam(partName = "requestcommonheader", name = "RequestHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        hu.posta.xmlns.common.RequestHeaderType requestcommonheader,
        @WebParam(partName = "parameters", name = "GetLanguages", targetNamespace = "http://tempuri.org/")
        GetLanguages parameters,
        @WebParam(partName = "responsecommonheader", mode = WebParam.Mode.OUT, name = "ResponseHeader", targetNamespace = "http://xmlns.posta.hu/Common", header = true)
        javax.xml.ws.Holder<hu.posta.xmlns.common.ResponseHeaderType> responsecommonheader,
        @WebParam(partName = "parameters", mode = WebParam.Mode.OUT, name = "GetLanguagesResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<GetLanguagesResponse> parameters1
    );
}
